runtime: nodejs10
service: shortlist-ui

handlers:
  - url: /
    static_files: storybook-dist/index.html
    upload: storybook-dist/index.html

  - url: /(.*)
    static_files: storybook-dist/\1
    upload: storybook-dist/(.*)
