name: myShortlist-ui deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install root dependencies
        run: yarn

      - name: Build storybook
        run: npm run build:storybook

      - name: Deploy application
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{secrets.GCP_SA_KEY}}
        with:
          args: app deploy app.yml
