name: myShortlist-ui deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Build storybook
        run: npm run build:storybook

      - name: Google cloud auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy
        run: gcloud --project ${{ secrets.PROJECT_ID }} app deploy
